### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ondonadas** [badaix/snapos#3]
Hi guys!
Nice work, congrats!

Please I'm trying to put snapcast client inside one of my openwrt boxes. After follow the guide and start compilation process it stops showing this:+

`make[3]: Entering directory '/media/data/git.Wispeak/src/snapos/openwrt/aixlog'
Makefile:43: *** Download/default is missing the FILE field..  Stop.
make[3]: Leaving directory '/media/data/git.Wispeak/src/snapos/openwrt/aixlog'
package/Makefile:192: recipe for target 'package/snapos/aixlog/compile' failed
make[2]: *** [package/snapos/aixlog/compile] Error 2
make[2]: Leaving directory '/media/data/git.Wispeak/src/openwrt.1'
package/Makefile:189: recipe for target '/media/data/git.Wispeak/src/openwrt.1/staging_dir/target-mips_34kc_musl-1.1.12/stamp/.package_compile' failed
make[1]: *** [/media/data/git.Wispeak/src/openwrt.1/staging_dir/target-mips_34kc_musl-1.1.12/stamp/.package_compile] Error 2
make[1]: Leaving directory '/media/data/git.Wispeak/src/openwrt.1'
/media/data/git.Wispeak/src/openwrt.1/include/toplevel.mk:192: fallo en las instrucciones para el objetivo 'world'
make: *** [world] Error 2
`

As far I can see it is messing with aixlog but can't figure out where the problem is. Please any help on how to debug gurther this issue?
Regards,

**Comment by badaix** [comment]
What OpenWrt release did you use? The master or maybe v17.01.4?

**Comment by ondonadas** [comment]
I've used an old version I did download some month a go 
 DESIGNATED DRIVER (Bleeding Edge, r48753)
because the git clone git://git.openwrt.org/15.05/openwrt.git is not available.

Which is the recommended version?

**Comment by badaix** [comment]
There is no recommendation. I switched to LEDE and didn't test with OpenWrt, because OpenWrt seemed to stuck at the 2015 release.
Right now I'm building the current OpenWrt HEAD. In ~1h I should find out if I can reproduce this issue, so stay tuned ;)

**Comment by ondonadas** [comment]
oh! men you're great! I'm building it too, but I think that my computer takes longer :-)

**Comment by ondonadas** [comment]
My build just finished fine. No errors with head version. I'm impatient to test it.

BTW, it is possible to run snapcast server on AR9331 cpu running openwrt?

**Comment by badaix** [comment]
My OpenWrt head also just finished successfully (seems your machine is stronger than my Core2 Duo).
Maybe the older OpenWrt releases cannot properly handle the `PKG_SOURCE_PROTO:=git` and insist in having a file to download. Just a guess.
Sorry, I have no idea about the AR9331. Try it and you will know :)

**Comment by badaix** [comment]
If you need a specific older version, you can try to add this to `aixlog/Makefile` (copied from [here](https://github.com/openwrt/packages/issues/5180)): 
```
PKG_SOURCE:=$(PKG_NAME)-$(PKG_SOURCE_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_SOURCE_VERSION)
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_SOURCE_VERSION)
```
(add it below `PKG_SOURCE_VERSION:=v1.1.0`)

**Comment by ondonadas** [comment]
thank you... I'll test it, with head version I've kernel incompatibilities with [audio driver](https://github.com/franzflasch/ar9331-i2s-alsa)

**Comment by badaix** [comment]
any news? Can this be closed?

**Comment by ondonadas** [comment]
Thank you badaix!
