### ISSUE TITLE
Add opus to list of needed packges?

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapos#6]
Opus is a codec that offers a great compromise between quality and latency.

I suggest adding it to the list of packages the Snapos builds, for instance adding BR2_PACKAGE_OPUS to `package/snapcast/Config.in`.
(BR2_PACKAGE_OPUS_TOOLS might be the one needed, I need to check)

It uses very little extra space and makes the built-in snapcast more robust, I think.

Thanks!

**Comment by axelsimon** [comment]
I think I went a bit fast on this one, support for Opus as an encoder was never added to Snapcast:
https://github.com/badaix/snapcast/pull/4

**Comment by badaix** [comment]
In the meantime Snapcast supports Opus and Opus has been added to Snapdroid b2cae2ced094977d26c7d1d741f43084f1dfe37c
