### ISSUE TITLE
SnapOS with Snapclient 0.19

### ISSUE THREAD

**Issue by LeoSum8** [badaix/snapos#8]
Would it be enough to change line 7 in https://github.com/badaix/snapos/blob/master/buildroot-external/package/snapcast/snapcast.mk#L7 to generate an image with snapclient 0.19?

**Comment by badaix** [comment]
yes, or you use the develop branch, which is using the 0.19 and also some more recent kernel

**Comment by LeoSum8** [comment]
ok that seems to make more sense. Thanks!

**Comment by LeoSum8** [comment]
As I had some issues building the entire firmware image containing snapcast, I used a different way via the OpenWRT-SDK to build the up to date .ipk and install it on the standard image for my device .

This uses way less diskspace and time :)

And if I understand correctly, the OpenWRT flavor of SnapOS does nothing to the OpenWRT base system in terms of optimization, does it?

@badaix If you agree I could write up a pull request for the documentation. I think this could save people some time.

Other than that, I am amazed by the raspberry-pi buildroot clients. They boot and start playing in less than 10s for me. The OpenWRT takes almost a minute. I am wondering if the OpenWRT image could be striped to achieve faster boot times.

**Comment by badaix** [comment]
True, SnapOS does nothing to the base system, the PR would be highly appreciated!
Are you're buildroot raspberry clients using WiFi? Do you use the OpenWRT images also on Raspberries?

**Comment by LeoSum8** [comment]
Ok I will start on that PR then.

The raspberry clients are built after the SnapOS docs, so standard buildroot, no OpenWRT.
They Version 1 Raspberrys which connect via LAN, no WiFi, so I guess that gives them an unfair advantage over my OpenWRT clients which connect via WiFi.

I also found that the default `/etc/network/interfaces` in buildroot contains a line `wait-delay 15` which causes unnecessary delay. Using fixed IP and commenting out that line also shortens the time-to-music.
